In [20]:
import csv
with open("movies.csv") as f:
    data = list(csv.reader(f))
    header=data[0]
    data=data[1:]

In [23]:
def calculate(data,industry=None):
    ratings=[]
    for row in data:
        if row[3]!='NULL' and (not industry or row[1]==industry):
            ratings.append(float(row[3]))
    max_rating = max(ratings)
    min_rating = min(ratings)
    avg_rating = sum(ratings)/len(ratings)
    return max_rating, min_rating, avg_rating

In [25]:
max_rating, min_rating, avg_rating = calculate(data)
print(f"All records: min rating:{min_rating}, max rating:{max_rating}, avg rating:{avg_rating}")

max_rating, min_rating, avg_rating = calculate(data, industry="Bollywood")
print(f"Bpllywood records: min rating:{min_rating}, max rating:{max_rating}, avg rating:{avg_rating}")

max_rating, min_rating, avg_rating = calculate(data, industry="Hollywood")
print(f"Hollywood records: min rating:{min_rating}, max rating:{max_rating}, avg rating:{avg_rating}")

All records: min rating:1.9, max rating:9.3, avg rating:7.919444444444445
Bpllywood records: min rating:1.9, max rating:8.4, avg rating:7.656250000000001
Hollywood records: min rating:6.8, max rating:9.3, avg rating:8.130000000000003

In [1]:
import pandas as pd

In [7]:
df = pd.read_csv("movies.csv")
df.sample()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
27,PK,Bollywood,2014,8.1,Vinod Chopra Films,850.0,8540.0,Millions,INR,Hindi

In [8]:
df.imdb_rating

0     8.3
1     7.0
2     6.8
3     7.9
4     6.8
5     9.3
6     8.6
7     8.0
8     8.5
9     7.9
10    8.6
11    7.8
12    9.2
13    9.0
14    9.0
15    8.2
16    8.5
17    8.4
18    8.4
19    6.9
20    7.8
21    8.0
22    8.4
23    7.4
24    7.2
25    8.3
26    8.1
27    8.1
28    NaN
29    8.3
30    8.1
31    1.9
32    8.4
33    8.4
34    7.6
35    8.0
36    8.0
Name: imdb_rating, dtype: float64

In [9]:
df_h=df[df.industry=="Hollywood"]
df_h

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.00,954.8,Millions,USD,English
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.00,644.8,Millions,USD,English
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.00,854.0,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.00,670.0,Millions,USD,English
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.00,73.3,Millions,USD,English
6,Interstellar,Hollywood,2014,8.6,Warner Bros. Pictures,165.00,701.8,Millions,USD,English
7,The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,55.00,307.1,Millions,USD,English
8,Gladiator,Hollywood,2000,8.5,Universal Pictures,103.00,460.5,Millions,USD,English
9,Titanic,Hollywood,1997,7.9,Paramount Pictures,200.00,2202.0,Millions,USD,English
10,It's a Wonderful Life,Hollywood,1946,8.6,Liberty Films,3.18,3.3,Millions,USD,English
11,Avatar,Hollywood,2009,7.8,20th Century Fox,237.00,2847.0,Millions,USD,English
12,The Godfather,Hollywood,1972,9.2,Paramount Pictures,7.20,291.0,Millions,USD,English
13,The Dark Knight,Hollywood,2008,9.0,Syncopy,185.00,1006.0,Millions,USD,English
14,Schindler's List,Hollywood,1993,9.0,Universal Pictures,22.00,322.2,Millions,USD,English
15,Jurassic Park,Hollywood,1993,8.2,Universal Pictures,63.00,1046.0,Millions,USD,English
16,Parasite,Hollywood,2019,8.5,NaN,15.50,263.1,Millions,USD,English
17,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,400.00,2798.0,Millions,USD,English
18,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,400.00,2048.0,Millions,USD,English
19,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,216.70,370.6,Millions,USD,English
20,Captain America: The Winter Soldier,Hollywood,2014,7.8,Marvel Studios,177.00,714.4,Millions,USD,English

In [10]:
df_b=df[df.industry=="Bollywood"]
df_b

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali
21,Dilwale Dulhania Le Jayenge,Bollywood,1995,8.0,Yash Raj Films,400.0,2000.0,Millions,INR,Hindi
22,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,550.0,4000.0,Millions,INR,Hindi
23,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,390.0,1360.0,Millions,INR,Hindi
24,Bajirao Mastani,Bollywood,2015,7.2,NaN,1.4,3.5,Billions,INR,Hindi
25,Taare Zameen Par,Bollywood,2007,8.3,NaN,120.0,1350.0,Millions,INR,Hindi
26,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,100.0,410.0,Millions,INR,Hindi
27,PK,Bollywood,2014,8.1,Vinod Chopra Films,850.0,8540.0,Millions,INR,Hindi
28,Sanju,Bollywood,2018,NaN,Vinod Chopra Films,1.0,5.9,Billions,INR,Hindi
29,The Kashmir Files,Bollywood,2022,8.3,Zee Studios,250.0,3409.0,Millions,INR,Hindi
30,Bajrangi Bhaijaan,Bollywood,2015,8.1,Salman Khan Films,900.0,11690.0,Millions,INR,Hindi
31,Race 3,Bollywood,2018,1.9,Salman Khan Films,1.8,3.1,Billions,INR,Hindi
32,Shershaah,Bollywood,2021,8.4,Dharma Productions,500.0,950.0,Millions,INR,Hindi
33,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,1.0,12.5,Billions,INR,Kannada
34,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2.0,3.6,Billions,INR,Telugu
35,RRR,Bollywood,2022,8.0,DVV Entertainment,5.5,12.0,Billions,INR,Telugu
36,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,1.8,6.5,Billions,INR,Telugu

In [13]:
a,b,c=df_b.imdb_rating.min(),df_b.imdb_rating.max(),df_b.imdb_rating.mean()

In [14]:
a,b,c

(1.9, 8.4, 7.656250000000001)

In [15]:
a,b,c=df_h.imdb_rating.min(),df_h.imdb_rating.max(),df_h.imdb_rating.mean()

In [16]:
a,b,c

(6.8, 9.3, 8.130000000000003)

In [18]:
df.shape

(37, 10)

In [20]:
df.columns

Index(['title', 'industry', 'release_year', 'imdb_rating', 'studio', 'budget',
       'revenue', 'unit', 'currency', 'language'],
      dtype='object')

In [21]:
df.language.value_counts()

English    20
Hindi      12
Telugu      3
Bengali     1
Kannada     1
Name: language, dtype: int64

In [23]:
df[df.studio=='Marvel Studios']

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English
17,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,400.0,2798.0,Millions,USD,English
18,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,400.0,2048.0,Millions,USD,English
19,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,216.7,370.6,Millions,USD,English
20,Captain America: The Winter Soldier,Hollywood,2014,7.8,Marvel Studios,177.0,714.4,Millions,USD,English

In [24]:
df.describe()

       release_year  imdb_rating        budget        revenue
count     37.000000    36.000000     37.000000      37.000000
mean    2007.027027     7.919444   2084.975135    4117.135135
std       17.657995     1.204947  11477.487145   16372.462682
min     1946.000000     1.900000      1.000000       3.100000
25%     2001.000000     7.800000     15.500000     263.100000
50%     2014.000000     8.100000    165.000000     701.800000
75%     2018.000000     8.400000    250.000000    2000.000000
max     2022.000000     9.300000  70000.000000  100000.000000

In [25]:
c=df.imdb_rating.max()

In [26]:
c

9.3

In [29]:
df[(df.imdb_rating==c) | (df.imdb_rating==df.imdb_rating.min())]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.0,73.3,Millions,USD,English
31,Race 3,Bollywood,2018,1.9,Salman Khan Films,1.8,3.1,Billions,INR,Hindi

In [31]:
df["age"]=df["release_year"].apply(lambda x: 2023-x)
df

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.00,100000.0,Thousands,INR,Bengali,68
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.00,954.8,Millions,USD,English,1
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.00,644.8,Millions,USD,English,10
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.00,854.0,Millions,USD,English,6
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.00,670.0,Millions,USD,English,1
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.00,73.3,Millions,USD,English,29
6,Interstellar,Hollywood,2014,8.6,Warner Bros. Pictures,165.00,701.8,Millions,USD,English,9
7,The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,55.00,307.1,Millions,USD,English,17
8,Gladiator,Hollywood,2000,8.5,Universal Pictures,103.00,460.5,Millions,USD,English,23
9,Titanic,Hollywood,1997,7.9,Paramount Pictures,200.00,2202.0,Millions,USD,English,26
10,It's a Wonderful Life,Hollywood,1946,8.6,Liberty Films,3.18,3.3,Millions,USD,English,77
11,Avatar,Hollywood,2009,7.8,20th Century Fox,237.00,2847.0,Millions,USD,English,14
12,The Godfather,Hollywood,1972,9.2,Paramount Pictures,7.20,291.0,Millions,USD,English,51
13,The Dark Knight,Hollywood,2008,9.0,Syncopy,185.00,1006.0,Millions,USD,English,15
14,Schindler's List,Hollywood,1993,9.0,Universal Pictures,22.00,322.2,Millions,USD,English,30
15,Jurassic Park,Hollywood,1993,8.2,Universal Pictures,63.00,1046.0,Millions,USD,English,30
16,Parasite,Hollywood,2019,8.5,NaN,15.50,263.1,Millions,USD,English,4
17,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,400.00,2798.0,Millions,USD,English,4
18,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,400.00,2048.0,Millions,USD,English,5
19,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,216.70,370.6,Millions,USD,English,12
20,Captain America: The Winter Soldier,Hollywood,2014,7.8,Marvel Studios,177.00,714.4,Millions,USD,English,9
21,Dilwale Dulhania Le Jayenge,Bollywood,1995,8.0,Yash Raj Films,400.00,2000.0,Millions,INR,Hindi,28
22,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,550.00,4000.0,Millions,INR,Hindi,14
23,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,390.00,1360.0,Millions,INR,Hindi,22
24,Bajirao Mastani,Bollywood,2015,7.2,NaN,1.40,3.5,Billions,INR,Hindi,8
25,Taare Zameen Par,Bollywood,2007,8.3,NaN,120.00,1350.0,Millions,INR,Hindi,16
26,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,100.00,410.0,Millions,INR,Hindi,20
27,PK,Bollywood,2014,8.1,Vinod Chopra Films,850.00,8540.0,Millions,INR,Hindi,9
28,Sanju,Bollywood,2018,NaN,Vinod Chopra Films,1.00,5.9,Billions,INR,Hindi,5
29,The Kashmir Files,Bollywood,2022,8.3,Zee Studios,250.00,3409.0,Millions,INR,Hindi,1
30,Bajrangi Bhaijaan,Bollywood,2015,8.1,Salman Khan Films,900.00,11690.0,Millions,INR,Hindi,8
31,Race 3,Bollywood,2018,1.9,Salman Khan Films,1.80,3.1,Billions,INR,Hindi,5
32,Shershaah,Bollywood,2021,8.4,Dharma Productions,500.00,950.0,Millions,INR,Hindi,2
33,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,1.00,12.5,Billions,INR,Kannada,1
34,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2.00,3.6,Billions,INR,Telugu,2
35,RRR,Bollywood,2022,8.0,DVV Entertainment,5.50,12.0,Billions,INR,Telugu,1
36,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,1.80,6.5,Billions,INR,Telugu,8

In [34]:
df["profit"]=df.apply(lambda x : x['revenue'] - x['budget'], axis=1)
df.head(4)

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age,profit
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali,68,30000.0
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English,1,754.8
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English,10,479.8
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English,6,674.0

In [36]:
df["age"]=df.apply(lambda x: 2023-x["release_year"],axis=1)
df

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age,profit
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.00,100000.0,Thousands,INR,Bengali,68,30000.00
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.00,954.8,Millions,USD,English,1,754.80
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.00,644.8,Millions,USD,English,10,479.80
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.00,854.0,Millions,USD,English,6,674.00
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.00,670.0,Millions,USD,English,1,420.00
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.00,73.3,Millions,USD,English,29,48.30
6,Interstellar,Hollywood,2014,8.6,Warner Bros. Pictures,165.00,701.8,Millions,USD,English,9,536.80
7,The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,55.00,307.1,Millions,USD,English,17,252.10
8,Gladiator,Hollywood,2000,8.5,Universal Pictures,103.00,460.5,Millions,USD,English,23,357.50
9,Titanic,Hollywood,1997,7.9,Paramount Pictures,200.00,2202.0,Millions,USD,English,26,2002.00
10,It's a Wonderful Life,Hollywood,1946,8.6,Liberty Films,3.18,3.3,Millions,USD,English,77,0.12
11,Avatar,Hollywood,2009,7.8,20th Century Fox,237.00,2847.0,Millions,USD,English,14,2610.00
12,The Godfather,Hollywood,1972,9.2,Paramount Pictures,7.20,291.0,Millions,USD,English,51,283.80
13,The Dark Knight,Hollywood,2008,9.0,Syncopy,185.00,1006.0,Millions,USD,English,15,821.00
14,Schindler's List,Hollywood,1993,9.0,Universal Pictures,22.00,322.2,Millions,USD,English,30,300.20
15,Jurassic Park,Hollywood,1993,8.2,Universal Pictures,63.00,1046.0,Millions,USD,English,30,983.00
16,Parasite,Hollywood,2019,8.5,NaN,15.50,263.1,Millions,USD,English,4,247.60
17,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,400.00,2798.0,Millions,USD,English,4,2398.00
18,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,400.00,2048.0,Millions,USD,English,5,1648.00
19,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,216.70,370.6,Millions,USD,English,12,153.90
20,Captain America: The Winter Soldier,Hollywood,2014,7.8,Marvel Studios,177.00,714.4,Millions,USD,English,9,537.40
21,Dilwale Dulhania Le Jayenge,Bollywood,1995,8.0,Yash Raj Films,400.00,2000.0,Millions,INR,Hindi,28,1600.00
22,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,550.00,4000.0,Millions,INR,Hindi,14,3450.00
23,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,390.00,1360.0,Millions,INR,Hindi,22,970.00
24,Bajirao Mastani,Bollywood,2015,7.2,NaN,1.40,3.5,Billions,INR,Hindi,8,2.10
25,Taare Zameen Par,Bollywood,2007,8.3,NaN,120.00,1350.0,Millions,INR,Hindi,16,1230.00
26,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,100.00,410.0,Millions,INR,Hindi,20,310.00
27,PK,Bollywood,2014,8.1,Vinod Chopra Films,850.00,8540.0,Millions,INR,Hindi,9,7690.00
28,Sanju,Bollywood,2018,NaN,Vinod Chopra Films,1.00,5.9,Billions,INR,Hindi,5,4.90
29,The Kashmir Files,Bollywood,2022,8.3,Zee Studios,250.00,3409.0,Millions,INR,Hindi,1,3159.00
30,Bajrangi Bhaijaan,Bollywood,2015,8.1,Salman Khan Films,900.00,11690.0,Millions,INR,Hindi,8,10790.00
31,Race 3,Bollywood,2018,1.9,Salman Khan Films,1.80,3.1,Billions,INR,Hindi,5,1.30
32,Shershaah,Bollywood,2021,8.4,Dharma Productions,500.00,950.0,Millions,INR,Hindi,2,450.00
33,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,1.00,12.5,Billions,INR,Kannada,1,11.50
34,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2.00,3.6,Billions,INR,Telugu,2,1.60
35,RRR,Bollywood,2022,8.0,DVV Entertainment,5.50,12.0,Billions,INR,Telugu,1,6.50
36,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,1.80,6.5,Billions,INR,Telugu,8,4.70

In [37]:
df.set_index('title',inplace=True)
df.head()

,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age,profit
title,,,,,,,,,,,
Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali,68,30000.0
Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English,1,754.8
Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English,10,479.8
Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English,6,674.0
Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English,1,420.0

In [44]:
df.loc[['Pather Panchali','Doctor Strange in the Multiverse of Madness']]

,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age,profit
title,,,,,,,,,,,
Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali,68,30000.0
Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English,1,754.8

In [47]:
df.loc[0]

KeyError: 0